# This is a basic workflow to help you get started with Actions

name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Setup SDKs
        run: |
          curl https://github.com/swiftwasm/swift/releases/download/swift-wasm-5.6.0-RELEASE/swift-wasm-5.6.0-RELEASE-macos_x86_64.pkg -L -o swift-wasm-toolchain.pkg
          sudo installer -pkg swift-wasm-toolchain.pkg -target /
          brew install wabt
          brew install binaryen

      - run: npm install
      - run: npm run build
      
      - run: tar -czvf dist.tgz dist/
      
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist.tgz
