# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Setup SDKs
        run: |
          curl https://github.com/swiftwasm/swift/releases/download/swift-wasm-5.7.1-RELEASE/swift-wasm-5.7.1-RELEASE-macos_x86_64.pkg -L -o swift-wasm-toolchain.pkg
          sudo installer -pkg swift-wasm-toolchain.pkg -target /
          brew install wabt
          brew install binaryen

      - run: npm install
      - run: npm run build
      
      - name: Test
        run: cd tests && npm install && npm run test
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
